ShowNow/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopNowBL.Models;
using ShopNowBL.Repository;

namespace ShowNow.Controllers
{
    public class CustomerController : Controller
    {
        CustomerRepo repo = new CustomerRepo();
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        //get customers
        public ActionResult ListCustomer()
        {
            var customers = repo.getAllCustomers();
            return View(customers);
        }

        //add customers
        public ActionResult AddCustomer()
        {
            tblCustomer objCustomer = new tblCustomer();
            return View(objCustomer);
        }
        [HttpPost]
        public ActionResult Create(tblCustomer objCustomer)
        {
            Boolean result = repo.addCustomer(objCustomer);
            if (result == true)
            {
                return RedirectToAction("ListCustomer");
            }
            else
            {
                return RedirectToAction("AddCustomer");
            }

        }

        //Update Customer
        public ActionResult Details(int id)
        {
            var objCustomer = repo.getCustomerById(id);
            return View("AddCustomer", objCustomer);
        }

        public ActionResult Delete(int id)
        {
            var objCustomer = repo.DeleteCustomerById(id);
            return RedirectToAction("ListCustomer");
        }

        public ActionResult SaveCustomerAjax(string Id,string CustomerName, string MobileNo)
        {
            tblCustomer objData = new tblCustomer();
            if (!string.IsNullOrEmpty(Id))
            {
                objData.Id = Convert.ToInt32(Id);
            }
           
            objData.CustomerName = CustomerName;
            objData.MobileNo = MobileNo;
            var result = repo.addCustomer(objData);
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetCustomerById(string Id)
        {
            tblCustomer customer = repo.getCustomerById(Convert.ToInt32(Id));
            return Json(customer, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteCustomer(string Id)
        {
            var result = repo.DeleteCustomerById(Convert.ToInt32(Id));
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCustomerByNumber(string MobileNo)
        {
            tblCustomer customer = repo.getCustomerByMobileNo(MobileNo);
            return Json(customer, JsonRequestBehavior.AllowGet);
        }
    }
}

ShowNow/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopNowBL.Models;
using ShopNowBL.Repository;
using ShowNow.ViewModels;
using Rotativa;
using System.IO;
using System.Net.Mail;
using System.Net;


namespace ShowNow.Controllers
{
    public class TransactionController : Controller
    {
        TransactionRepo TR = new TransactionRepo();
        StockRepo SR = new StockRepo();
        CustomerRepo CR = new CustomerRepo();
        // GET: Transaction
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveTransaction(string Id, string TotalQty, string TotalAmount,string PayMethod,decimal totalDisc,decimal totalgst, List<tblTransactionItem> TItems)
        {
            //save transaction
            tblTransaction objData = new tblTransaction();
            objData.TotalQty = Convert.ToInt32(TotalQty);
            objData.InvoiceAmount = Convert.ToDecimal(TotalAmount);
            objData.PaymentMethod = PayMethod;
            objData.CustomerId = Convert.ToInt32(Id);
            objData.InvoiceNo = TR.GenerateId();
            objData.GST = totalgst;
            objData.TotalDiscount = totalDisc;
            var result = TR.SaveTransaction(objData);
            
            var itemResult = false;
            //save transaction Items
           // List<tblTransactionItem> lstItems = TItems;


           if (result)
            {
                
                foreach(tblTransactionItem T in TItems)
                {
                    tblTransactionItem objItem = new tblTransactionItem();
                    objItem.InvoiceId = objData.InvoiceNo;
                    objItem.ProductId = T.ProductId;
                    objItem.Price = T.Price;
                    objItem.Qty = T.Qty;
                    itemResult=TR.SaveTransactionItems(objItem);
                    //update stock
                    tblStock stock =  SR.FindProductById(objItem.ProductId);
                    stock.ProductQty -= Convert.ToInt32(objItem.Qty);
                    SR.saveProduct(stock);
                }
            }

            return Json(itemResult, JsonRequestBehavior.AllowGet);

        }

        public ActionResult SaveTransactions(string Id, string TotalQty, string TotalAmount, string PayMethod, decimal totalDisc, decimal totalgst, List<tblTransactionItem> TItems)
        {
            //save transaction
            tblTransaction objData = new tblTransaction();
            objData.TotalQty = Convert.ToInt32(TotalQty);
            objData.InvoiceAmount = Convert.ToDecimal(TotalAmount);
            objData.PaymentMethod = PayMethod;
            objData.CustomerId = Convert.ToInt32(Id);
            objData.InvoiceNo = TR.GenerateId();
            objData.GST = totalgst;
            objData.TotalDiscount = totalDisc;
          
            List<tblTransactionItem> lstItems = TItems;

            tblTransaction result = TR.SaveTransactions(objData, lstItems);

         
            return Json(result, JsonRequestBehavior.AllowGet);

        }
       
        public ActionResult TransactionPage()
        {
            TransactionModel transactionModel = new TransactionModel();
            transactionModel.lstProduct = SR.getAllProduct();
            return View(transactionModel);
        }

        public ActionResult GetProductById(string Id)
        {
            tblStock stock = SR.FindProductById(Convert.ToInt32(Id));
            return Json(stock, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveTransactionViewModel(TransactionModel objData)
        {
            objData.objTransaction.InvoiceNo = TR.GenerateId();
            objData.objItem.InvoiceId = objData.objTransaction.InvoiceNo;
            objData.objItem.Qty = objData.objTransaction.TotalQty;

            TR.CaptureTransaction(objData.objItem,objData.objTransaction,objData.objCustmore);
            return RedirectToAction("TransactionPage");
        }

        public ActionResult BillPreview(string InvoiceNo,string hide, string receiver)
        {
            //InvoiceNo = "6cae7dcfd0e4607b";
            TransactionModel transactionModel = new TransactionModel();

            transactionModel.lstItems = TR.GetTransactionItemsByInvoiceNo(InvoiceNo);
            transactionModel.objTransaction = TR.GetTransactionByInvoiceNo(InvoiceNo);
            transactionModel.objCustmore = CR.getCustomerById(transactionModel.objTransaction.CustomerId);

            ViewBag.receiver = receiver;
            ViewBag.Hide = hide;

            return PartialView("_BillPreview",transactionModel);
        }

        public ActionResult PrintInvoice(string InvoiceNo,string receiver)
        {
            var a = new ViewAsPdf();
            a.ViewName = "_BillPreview";
            TransactionModel transactionModel = new TransactionModel();
            transactionModel.lstItems = TR.GetTransactionItemsByInvoiceNo(InvoiceNo);
            transactionModel.objTransaction = TR.GetTransactionByInvoiceNo(InvoiceNo);
            transactionModel.objCustmore = CR.getCustomerById(transactionModel.objTransaction.CustomerId);

            ViewBag.InvoiceId = InvoiceNo;
            ViewBag.Hide = 1;

            a.Model = transactionModel;
            var pdfBytes = a.BuildFile(this.ControllerContext);

            // Optionally save the PDF to server in a proper IIS location.
            var fileName = transactionModel.objCustmore.CustomerName+transactionModel.objTransaction.InvoiceNo + ".pdf";
            var path = Server.MapPath("~/Temp/" + fileName);
            //var path = "https://liacrm.com/CRM_Publish/Temp/" + fileName;
            System.IO.File.WriteAllBytes(path, pdfBytes);

            // return ActionResult
            MemoryStream ms = new MemoryStream(pdfBytes);

            
            //Email sending
            try
            {
                var senderEmail = new MailAddress("kartikgund2@gmail.com", "Kartik");
                var receiverEmail = new MailAddress(receiver, "Receiver");
                var password = "rgpljlpevjrezdpq";
                var sub = "Invoice For Your Purchase";
                var body = "Dear "+ transactionModel.objCustmore.CustomerName+ " Thank you for your purchase your Invoice is here, Visit Again!!";

                MailMessage message = new MailMessage();
                message.To.Add(receiver);// Email-ID of Receiver  
                message.Subject = sub;// Subject of Email  
                message.From = senderEmail;// Email-ID of Sender  
                message.IsBodyHtml = true;
                Attachment data = new Attachment(ms, fileName, "application/pdf");
                message.Attachments.Add(data);
                message.Body = body;
                SmtpClient SmtpMail = new SmtpClient();

                SmtpMail.Host = "smtp.gmail.com";
                SmtpMail.Port = 587;
                SmtpMail.EnableSsl = true;
                SmtpMail.DeliveryMethod = SmtpDeliveryMethod.Network;
                SmtpMail.UseDefaultCredentials = false;
                SmtpMail.Credentials = new NetworkCredential(senderEmail.Address, password);
                SmtpMail.Send(message);
                
            }
            catch (Exception)
            {
                ViewBag.Error = "Some Error";
            }

            return RedirectToAction("BuyProduct", "Stocks");
        }
    }
}

ShowNow/Views/Transaction/TransactionPage.cshtml
@model ShowNow.ViewModels.TransactionModel
@{
    ViewBag.Title = "TransactionPage";
}

<h2>TransactionPage</h2>
@using (Html.BeginForm("SaveTransactionViewModel", "Transaction", FormMethod.Post))
{
<div class="form-horizontal">
    <div class="form-group">
        @Html.Label("ProductName", "Product Name", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Product Name", new SelectList(Model.lstProduct, "Id", "ProductName"), "Please Select",
    new { @id = "product", @class = "form-control", @onchange = "GetProduct(this.value)" })

        </div>
    </div>
    <div class="form-group">
        @Html.HiddenFor(model => model.objItem.ProductId, new { id = "txtPId" })
    </div>
    <div class="form-group">
        @Html.Label("Qty", " Quantity", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objTransaction.TotalQty, new { type = "number", min = "0" })

        </div>
    </div>

    <div class="form-group">
        @Html.Label("Price", "Amount", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objItem.Price, new { @readonly = "readonly", id = "txtAmount" })

        </div>
    </div>

    <div class="form-group">
        @Html.Label("Discount", "Discount", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objTransaction.TotalDiscount, new { @readonly = "readonly", id = "txtDiscount" })

        </div>
    </div>
    
    <div class="form-group">
        @Html.Label("GST", "GST", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objTransaction.GST, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Total Amount", "TotalAmount", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objTransaction.InvoiceAmount, new { @readonly = "readonly", id = "txtTotalAmount" })

        </div>
    </div>

    <div class="form-group">
        @Html.Label("MobileNo", "Mobile No", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objCustmore.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Name", "Customer Name", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objCustmore.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>


    <div class="form-group">
        @Html.HiddenFor(model => model.objCustmore.Id)
    </div>
    <div class="form-group">
        
        @Html.HiddenFor(model => model.objTransaction.CustomerId, new { id = "hdnCId" })
    </div>

    <div class="form-group">
        @Html.Label("InvoiceNo", "Invoice No", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.objItem.InvoiceId, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("PaymentMethod", "Payment Method", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.objTransaction.PaymentMethod, new SelectList(Model.BOProducts(), "Value", "Text"), "Please Select", htmlAttributes: new { @class = "input40", @id = "ddlBOProduct1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Pay Bill" class="btn btn-success" />
        </div>
    </div>

</div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#objTransaction_GST').focusout(function () {
            calc_total();

        });

        $('#objCustmore_MobileNo').focusout(function () {
            GetCustomer();

        });
    });

    function GetProduct(id) {
        //alert(id);
        $.ajax({
            type:"POST",
            url: '@Url.Action("GetProductById","Transaction")',
            data: '{Id: ' + JSON.stringify($("#product").val()) + '}',
            contentType: 'application/json; charset=utf-8',
            dataType:'json',
            success: function (result) {
                $('#txtAmount').val(result.SellingPrice);
                $('#txtDiscount').val(result.Discount);
                $('#txtPId').val(result.Id);
            },
            error: function (result) {
                console.log(result);
            }
        });
    }

    function calc_total() {
        var BasicAmt = parseFloat($('#txtAmount').val()) * parseFloat($('#objTransaction_TotalQty').val()),
            discount = BasicAmt * ($('#txtDiscount').val() / 100),
            gst = (BasicAmt - discount) * ($('#objTransaction_GST').val() / 100),
            totalAmount = BasicAmt - discount + gst;
        $('#txtTotalAmount').val(totalAmount);
    }

    function GetCustomer() {

       $.ajax({
            type:"POST",
            url: '@Url.Action("GetCustomerByNumber", "Customer")',
           data: '{MobileNo: ' + JSON.stringify($("#objCustmore_MobileNo").val()) + '}',
            contentType: 'application/json; charset=utf-8',
            dataType:'json',
           success: function (result) {
               $('#objCustmore_Id').val(result.Id);
               $('#hdnCId').val(result.Id);
               $('#objCustmore_CustomerName').val(result.CustomerName);
               alert("Registered Customer")
             //  document.getElementById("btnSave").style.display = "block";

            },
           error: function (result) {
               alert("Not registered.!!");
              // document.getElementById("myForm").style.display = "block";
              // openForm();

            }
        });
        }

        function feedTable() {
           // e.preventDefault();
            if (!this.snNo) this.snNo = 1;
            var Name = $('#product').val(),
                Id = $('#txtPId').val(),
                SPrice = $('#txtAmount').val(),
                Discount = $('#txtDiscount').val(),
                Qty = $('#objTransaction_TotalQty').val(),
               
                Price = (SPrice * Qty) - (SPrice * Qty * (Discount / 100))
            $('#record').append(
                "<tr><td>" + Id + "</td>" +
                "<td>" + Name + "</td>" +
                "<td>" + SPrice + "</td>" +
                "<td>" + Discount + "</td>" +
                "<td>" + Qty + "</td>" +
       
                "<td class='total'>" + Price + "</td></tr > "
            )
            this.snNo += 1;
            calc_total();

            $('#product').val(""),
                 $('#txtPId').val(""),
                $('#txtAmount').val(""),
                 $('#txtDiscount').val(""),
                 $('#objTransaction_TotalQty').val("")
           @* var count = $('#record tr').length - 1;
            console.log(count);*@
        }


</script>

ShowNow/Views/Transaction/_BillPreview.cshtml
@model ShowNow.ViewModels.TransactionModel

<h1>Invoice</h1>
<hr />
<div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Invoice No :</label>
        @Model.objTransaction.InvoiceNo

    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Invoice Date :</label>
        @Model.objTransaction.InvoiceDate
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Customer Name :</label>
        @Model.objCustmore.CustomerName
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="MobileNo">Mobile No  :</label>
        @Model.objCustmore.MobileNo
    </div>
</div>
<hr />
<table class="table table-bordered table-condensed table-hover">
    <tr>
        <th>Product ID</th>
        <th>Product Name</th>
        <th>Quantity</th>
        <th>Price</th>

    </tr>

    @foreach (var item in Model.lstItems)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.tblStock.ProductName</td>
            <td>@item.Qty</td>
            <td>@item.Price</td>
        </tr>
    }
</table>
<br />
<div class="form-group">
    <label class="control-label col-sm-2" for="TotalDiscount">Total Discount  :</label>
    @Model.objTransaction.TotalDiscount
</div>
<div class="form-group">
    <label class="control-label col-sm-2" for="TotalGST">Total GST  :</label>
    @Model.objTransaction.GST
</div>


<div class="form-group">
    <label class="control-label col-sm-2" for="TotalAmount">Total Amount  :</label>
    @Model.objTransaction.InvoiceAmount
</div>


@if (string.IsNullOrEmpty(Convert.ToString(ViewBag.Hide)))
{

        <a href=@Url.Action("PrintInvoice", "Transaction", new { @InvoiceNo = Model.objTransaction.InvoiceNo,@receiver=ViewBag.receiver })>Print</a>
}